component:
  name: landing_zone_gateway_nat
  dependsOn:
    - ../landing_zone_eip
    - ../landing_zone_subnet
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_gateway_nat/terraform.tfstate
    data:
      aws_vpc:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_vpc_cidr_blocks)}'
          cidr_block: '${element(var.landing_zone_vpc_cidr_blocks, count.index)}'
      aws_subnet:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_subnet_cidr_blocks)}'
          cidr_block: '${element(var.landing_zone_subnet_cidr_blocks, count.index)}'
          vpc_id: '${element(data.aws_vpc.selected.*.id, count.index)}'
      aws_eip:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_eip_public_ips)}'
          public_ip: '${element(var.landing_zone_eip_public_ips, count.index)}'
    resource:
      aws_nat_gateway:
        landing_zone_gateway_nat:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(data.aws_subnet.selected.*.id)}'
          allocation_id: '${element(data.aws_eip.selected.*.id, count.index)}'
          subnet_id: '${element(data.aws_subnet.selected.*.id, count.index)}'
          tags: >-
            ${merge(var.landing_zone_gateway_nat_tags, map("Name", "Landing Zone
            Nat Gateway ${element(data.aws_subnet.selected.*.id,
            count.index)}"))}
    output:
      ids:
        value: '${aws_nat_gateway.landing_zone_gateway_nat.*.id}'
      thub_ids:
        value: '${aws_nat_gateway.landing_zone_gateway_nat.*.id}'
      network_interface_ids:
        value: '${aws_nat_gateway.landing_zone_gateway_nat.*.network_interface_id}'
      landing_zone_gateway_nat_ids:
        value: '${aws_nat_gateway.landing_zone_gateway_nat.*.id}'
      landing_zone_gateway_nat_network_interface_ids:
        value: '${aws_nat_gateway.landing_zone_gateway_nat.*.network_interface_id}'
terraform:
  varFile:
    - ../mitocgroup_tfvars/landing_zone_gateway_nat/default.tfvars
