## local config
component:
  name: landing_zone_organization
  template:
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-aws-landing-zone/landing_zone_organization/terraform.tfstate
    resource:
      aws_organizations_organization:
        landing_zone_organization:
          aws_service_access_principals: '${var.landing_zone_organization_service_access_principals}'
          enabled_policy_types: '${var.landing_zone_organization_enabled_policy_types}'
          feature_set: '${var.landing_zone_organization_feature_set}'
    output:
      id:
        value: '${aws_organizations_organization.landing_zone_organization.id}'
      thub_id:
        value: '${aws_organizations_organization.landing_zone_organization.id}'
      master_account_id:
        value: '${aws_organizations_organization.landing_zone_organization.master_account_id}'
      arn:
        value: '${aws_organizations_organization.landing_zone_organization.arn}'
      master_account_arn:
        value: '${aws_organizations_organization.landing_zone_organization.master_account_arn}'
      master_account_email:
        value: '${aws_organizations_organization.landing_zone_organization.master_account_email}'
      accounts:
        value: '${aws_organizations_organization.landing_zone_organization.accounts}'
      roots:
        value: '${aws_organizations_organization.landing_zone_organization.roots}'
