component:
  name: landing_zone_security_group
  dependsOn:
    - ../landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_security_group/terraform.tfstate
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_vpc_data_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
      elements_landing_zone_security_group_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_tags_element"]
      elements_landing_zone_security_group_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_resource"]
      elements_landing_zone_security_group_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_resource"])
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_vpc_data_count
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
    resource:
      aws_security_group:
        landing_zone_security_group:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_security_group_count
          name: >-
            local.elements_landing_zone_security_group_map["config_${count.index}"]["name"]
          description: >-
            local.elements_landing_zone_security_group_map["config_${count.index}"]["description"]
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          tags: >-
            local.elements_landing_zone_security_group_tags_map["config_${count.index}"]
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group.landing_zone_security_group.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group.landing_zone_security_group.*.id)
      landing_zone_security_group_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group.landing_zone_security_group.*.id)
terraform:
  varFile:
    - ../../local-terraform/landing_zone_security_group/config.tfvars
