## local config
component:
  name: landing_zone_network_acl_rules_private
  dependsOn:
  - '../landing_zone_network_acl_private'
  template:
    terraform:
      backend:
        local:
          path: ${local.component["local"]}/landing_zone_network_acl_rules_private/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_network_acl_private:
          backend: local
          config:
            path: '${local.component["local"]}/landing_zone_network_acl_private/terraform.tfstate'
    resource:
      aws_network_acl_rule:
        landing_zone_network_acl_rules_private:
          count: ${length(var.landing_zone_network_acl_rules_private_rule_numbers)}
          network_acl_id: '${data.terraform_remote_state.landing_zone_network_acl_private.thub_id}'
          rule_number: '${element(var.landing_zone_network_acl_rules_private_rule_numbers, count.index)}'
          protocol: '${element(var.landing_zone_network_acl_rules_private_protocols, count.index)}'
          rule_action: '${element(var.landing_zone_network_acl_rules_private_rule_actions, count.index)}'
          egress: '${element(var.landing_zone_network_acl_rules_private_egress, count.index)}'
          cidr_block: '${element(var.landing_zone_network_acl_rules_private_cidr_blocks, count.index)}'
terraform:
  varFile:
    - >-
      s3://terraform-aws-landing-zone-mitocgroup/tfvars/landing_zone_network_acl_rules_private/default.tfvars
