component:
  name: landing_zone_cloudtrail_s3_bucket
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_cloudtrail_s3_bucket/terraform.tfstate
    resource:
      aws_s3_bucket:
        landing_zone_cloudtrail_s3_bucket:
          provider: '${tfvar.terrahub["provider_alias"]}'
          bucket: '${var.landing_zone_cloudtrail_s3_bucket_name}-${var.region}'
          versioning:
            enabled: '${var.landing_zone_cloudtrail_s3_bucket_versioning}'
    output:
      id:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.id}'
      thub_id:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.id}'
      arn:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.arn}'
      bucket:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.bucket}'
      landing_zone_cloudtrail_s3_bucket_id:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.id}'
      landing_zone_cloudtrail_s3_bucket_arn:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.arn}'
      landing_zone_cloudtrail_s3_bucket_bucket:
        value: '${aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.bucket}'
