component:
  name: landing_zone_cloudtrail_s3_bucket
  template:
    locals:
      elements_landing_zone_cloudtrail_s3_bucket_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_cloudtrail_s3_bucket_resource"]
    resource:
      aws_s3_bucket:
        landing_zone_cloudtrail_s3_bucket:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(local.elements_landing_zone_cloudtrail_s3_bucket_map)
          bucket: >-
            ${local.elements_landing_zone_cloudtrail_s3_bucket_map["config_${count.index}"]["name"]}-${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_region}
          versioning:
            enabled: >-
              local.elements_landing_zone_cloudtrail_s3_bucket_map["config_${count.index}"]["versioning"]
    output:
      id:
        value: aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.*.id
      thub_id:
        value: aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.*.id
      arn:
        value: aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.*.arn
      landing_zone_cloudtrail_s3_bucket_id:
        value: >-
          { for s3 in aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.*: s3.id
          => s3.id }
      landing_zone_cloudtrail_s3_bucket_arn:
        value: >-
          { for s3 in aws_s3_bucket.landing_zone_cloudtrail_s3_bucket.*: s3.id
          => s3.arn }
