component:
  name: landing_zone_eip
  template:
    locals:
      elements_landing_zone_eip_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_eip_tags"]
      elements_landing_zone_eip_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_eip_resource"]
    resource:
      aws_eip:
        landing_zone_eip:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_eip_resource"])
          tags: 'local.elements_landing_zone_eip_tags_map["config_${count.index}"]'
          vpc: 'local.elements_landing_zone_eip_map["config_${count.index}"]["vpc"]'
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_eip.landing_zone_eip.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_eip.landing_zone_eip.*.id)
      public_ips:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_eip.landing_zone_eip.*.public_ip)
      landing_zone_eip_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_eip.landing_zone_eip.*.id)
      landing_zone_eip_public_ips:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_eip.landing_zone_eip.*.public_ip)
