component:
  name: landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: '${tfvar.terrahub["tfstate_path"]}/landing_zone_vpc/terraform.tfstate'
    locals:
      elements_landing_zone_vpc_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_resource"]
      elements_landing_zone_vpc_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_tags_element"]
    resource:
      aws_vpc:
        landing_zone_vpc:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_resource"])
          cidr_block: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["cidr_block"]
          instance_tenancy: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["instance_tenancy"]
          enable_dns_support: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["enable_dns_support"]
          assign_generated_ipv6_cidr_block: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["assign_generated_ipv6_cidr_block"]
          enable_classiclink: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["enable_classiclink"]
          enable_dns_hostnames: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["enable_dns_hostnames"]
          enable_classiclink_dns_support: >-
            local.elements_landing_zone_vpc_map["config_${count.index}"]["enable_classiclink_dns_support"]
          tags: 'local.elements_landing_zone_vpc_tags_map["config_${count.index}"]'
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_vpc.landing_zone_vpc.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_vpc.landing_zone_vpc.*.id)
      arns:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_vpc.landing_zone_vpc.*.arn)
      landing_zone_vpc_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_vpc.landing_zone_vpc.*.id)
      landing_zone_vpc_arns:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_vpc.landing_zone_vpc.*.arn)
terraform:
  varFile:
    - ../../local-terraform/landing_zone_vpc/config.tfvars
