project:
  name: terraform-aws-landing-zone
  code: eef16dcf
  include:
    - .
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'
terraform:
  varFile:
    - default.tfvars
  version: 0.12.12
template:
  provider:
    - aws:
        region: var.region
        allowed_account_ids:
          - var.account_id
    - aws:
        alias: default
        region: var.region
        allowed_account_ids:
          - var.account_id
    - aws:
        alias: bloomingaprons
        region: var.bloomingaprons_region
        assume_role:
          - role_arn: >-
              arn:aws:iam::${tfvar.terrahub["bloomingaprons_account_id"]}:role/OrganizationAccountAccessRole
            session_name: var.bloomingaprons_account_id
    - aws:
        alias: eurechean
        region: var.eurechean_region
        assume_role:
          - role_arn: >-
              arn:aws:iam::${tfvar.terrahub["eurechean_account_id"]}:role/OrganizationAccountAccessRole
            session_name: var.eurechean_account_id
    - aws:
        alias: mitocgroup
        region: var.mitocgroup_region
        assume_role:
          - role_arn: >-
              arn:aws:iam::${tfvar.terrahub["mitocgroup_account_id"]}:role/OrganizationAccountAccessRole
            session_name: var.mitocgroup_account_id
    - aws:
        alias: terrahub
        region: var.terrahub_region
        assume_role:
          - role_arn: >-
              arn:aws:iam::${tfvar.terrahub["terrahub_account_id"]}:role/OrganizationAccountAccessRole
            session_name: var.terrahub_account_id
    - aws:
        alias: vcalmic
        region: var.vcalmic_region
        assume_role:
          - role_arn: >-
              arn:aws:iam::${tfvar.terrahub["vcalmic_account_id"]}:role/OrganizationAccountAccessRole
            session_name: var.vcalmic_account_id
  tfvars:
    account_id: 722084099005
    region: us-east-1
    bloomingaprons_account_id: 490643292278
    bloomingaprons_region: us-east-1
    default_account_id: 722084099005
    default_region: us-east-1
    eurechean_account_id: 643695102975
    eurechean_region: us-east-1
    mitocgroup_account_id: 492198229272
    mitocgroup_region: us-east-1
    terrahub_account_id: 600605919324
    terrahub_region: us-east-1
    vcalmic_account_id: 300672210419
    vcalmic_region: us-east-1
  terraform:
    backend:
      local:
        path: >-
          /tmp/.terrahub/landing_zone/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
