project:
  name: terraform-aws-landing-zone
  code: eef16dcf
  include:
    - .
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'
terraform:
  varFile:
    - default.tfvars
template:
  provider:
    aws:
      region: '${var.region}'
      allowed_account_ids:
        - '${var.account_id}'
