component:
  name: landing_zone_tgw_route_table
  dependsOn:
    - landing_zone_gateway_tgw
  template:
    locals:
      elements_landing_zone_route_table_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_tgw_route_table_resource"]
      elements_landing_zone_tgw_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_tgw_data"]
    data:
      aws_ec2_transit_gateway:
        gateway_tgw_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_tgw_data"])
          filter:
            - name: options.amazon-side-asn
              values:
                - >-
                  local.elements_landing_zone_tgw_data_map["config_${count.index}"]["amazon_side_asn"]
    resource:
      aws_ec2_transit_gateway_route_table:
        landing_zone_tgw_route_table:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_tgw_route_table_resource"])
          transit_gateway_id: >-
            element(data.aws_ec2_transit_gateway.gateway_tgw_selected.*.id,
            count.index)
          tags: 'local.elements_landing_zone_route_table_map["config_${count.index}"]'
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ec2_transit_gateway_route_table.landing_zone_tgw_route_table.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ec2_transit_gateway_route_table.landing_zone_tgw_route_table.*.id)
      landing_zone_tgw_route_table_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ec2_transit_gateway_route_table.landing_zone_tgw_route_table.*.id)
