## local config
component:
  name: landing_zone_route_table_association
  dependsOn:
  - '../landing_zone_route_table'
  - '../landing_zone_subnet_public'
  template:
    terraform:
      backend:
        local:
          path: ${local.component["local"]}/landing_zone_route_table_association/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_route_table:
          backend: local
          config:
            path: '${local.component["local"]}/landing_zone_route_table/terraform.tfstate'
        landing_zone_subnet_public:
          backend: local
          config:
            path: '${local.component["local"]}/landing_zone_subnet_public/terraform.tfstate'
    resource:
      aws_route_table_association:
        landing_zone_route_table_association:
          count: '${length(data.terraform_remote_state.landing_zone_subnet_public.thub_ids)}'
          subnet_id: '${element(data.terraform_remote_state.landing_zone_subnet_public.thub_ids, count.index)}'
          route_table_id: '${data.terraform_remote_state.landing_zone_route_table.thub_id}'
    output:
      ids:
        value: '${aws_route_table_association.landing_zone_route_table_association.*.id}'
      thub_ids:
        value: '${aws_route_table_association.landing_zone_route_table_association.*.id}'
      landing_zone_route_table_association_ids:
        value: '${aws_route_table_association.landing_zone_route_table_association.*.id}'
