component:
  name: landing_zone_route_table_association
  dependsOn:
    - ../landing_zone_route_table
    - ../landing_zone_subnet
  template:
    terraform:
      backend:
        local:
          path: >-
            ${local.component["local"]}/landing_zone_route_table_association/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_route_table:
          backend: local
          config:
            path: >-
              ${local.component["local"]}/landing_zone_route_table/terraform.tfstate
        landing_zone_subnet:
          backend: local
          config:
            path: '${local.component["local"]}/landing_zone_subnet/terraform.tfstate'
    resource:
      aws_route_table_association:
        landing_zone_route_table_association:
          count: '${length(var.landing_zone_route_table_association_relation)}'
          subnet_id: >-
            ${element(data.terraform_remote_state.landing_zone_subnet.thub_ids,
            element(split("/",
            element(var.landing_zone_route_table_association_relation,
            count.index)), 0))}
          route_table_id: >-
            ${element(data.terraform_remote_state.landing_zone_route_table.thub_ids,
            element(split("/",
            element(var.landing_zone_route_table_association_relation,
            count.index)), 1))}
    output:
      ids:
        value: >-
          ${aws_route_table_association.landing_zone_route_table_association.*.id}
      thub_ids:
        value: >-
          ${aws_route_table_association.landing_zone_route_table_association.*.id}
      landing_zone_route_table_association_ids:
        value: >-
          ${aws_route_table_association.landing_zone_route_table_association.*.id}
