component:
  name: landing_zone_route_table_association
  dependsOn:
    - ../landing_zone_route_table
    - ../landing_zone_subnet
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_route_table_association/terraform.tfstate
    data:
      aws_vpc:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_vpc_cidr_blocks)}'
          cidr_block: '${element(var.landing_zone_vpc_cidr_blocks, count.index)}'
      aws_subnet:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_subnet_cidr_blocks)}'
          cidr_block: '${element(var.landing_zone_subnet_cidr_blocks, count.index)}'
          vpc_id: '${element(data.aws_vpc.selected.*.id, count.index)}'
      aws_route_table:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_route_table_filters)}'
          vpc_id: '${element(data.aws_vpc.selected.*.id, count.index)}'
          filter:
            - name: 'tag:Name'
              values:
                - >-
                  ${element(split("|",
                  element(var.landing_zone_route_table_filters, count.index)),
                  0)}
            - name: association.main
              values:
                - >-
                  ${element(split("|",
                  element(var.landing_zone_route_table_filters, count.index)),
                  1)}
    resource:
      aws_route_table_association:
        landing_zone_route_table_association:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_route_table_association_relation)}'
          subnet_id: >-
            ${element(data.aws_subnet.selected.*.id, element(split("|",
            element(var.landing_zone_route_table_association_relation,
            count.index)), 0))}
          route_table_id: >-
            ${element(data.aws_route_table.selected.*.id, element(split("|",
            element(var.landing_zone_route_table_association_relation,
            count.index)), 1))}
    output:
      ids:
        value: >-
          ${aws_route_table_association.landing_zone_route_table_association.*.id}
      thub_ids:
        value: >-
          ${aws_route_table_association.landing_zone_route_table_association.*.id}
      landing_zone_route_table_association_ids:
        value: >-
          ${aws_route_table_association.landing_zone_route_table_association.*.id}
