## local config
component:
  name: landing_zone_code_build_role_policy
  dependsOn:
    - ../landing_zone_pipeline_artifact_s3_bucket
    - ../landing_zone_code_build_role
  template:
    terraform:
      backend:
        local:
          path: ${local.component["local"]}/landing_zone_code_build_role_policy/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_pipeline_artifact_s3_bucket:
          backend: local
          config:
            path: ${local.component["local"]}/landing_zone_pipeline_artifact_s3_bucket/terraform.tfstate
        landing_zone_code_build_role:
          backend: local
          config:
            path: ${local.component["local"]}/landing_zone_code_build_role/terraform.tfstate
      template_file:
        landing_zone_code_build_role_policy:
          template: '${file("${local.component["path"]}/iam_assume_policy.json.tpl")}'
          vars:
            artifact_s3_bucket_arn: ${data.terraform_remote_state.landing_zone_pipeline_artifact_s3_bucket.arn}'
            account_id: '${var.account_id}'
            region: '${var.region}'
    resource:
      aws_iam_role_policy:
        landing_zone_code_build_role_policy:
          name: '${var.landing_zone_code_build_role_policy_name}'
          policy: '${data.template_file.landing_zone_code_build_role_policy.rendered}'
          role: '${data.terraform_remote_state.landing_zone_code_build_role.id}'
    output:
      id:
        value: '${aws_iam_role_policy.landing_zone_code_build_role_policy.id}'
      thub_id:
        value: '${aws_iam_role_policy.landing_zone_code_build_role_policy.id}'
      name:
        value: '${aws_iam_role_policy.landing_zone_code_build_role_policy.name}'
