component:
  name: landing_zone_directory_service_directory
  template:
    locals:
      elements_landing_zone_subnet_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_data"]
      elements_landing_zone_subnet_data_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_data"])
      elements_landing_zone_directory_service_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_directory_service_resource"]
      elements_landing_zone_directory_service_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_directory_service_resource"])
    data:
      aws_vpc:
        default_vpc:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          default: true
      aws_subnet:
        default_subnet:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_subnet_data_count
          availability_zone: >-
            local.elements_landing_zone_subnet_data_map["config_${count.index}"]["availability_zone"]
          vpc_id: data.aws_vpc.default_vpc.id
    resource:
      aws_directory_service_directory:
        landing_zone_directory_service_directory:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_directory_service_count
          name: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["name"]
          short_name: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["short_name"]
          password: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["password"]
          alias: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["alias"]
          description: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["description"]
          edition: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["edition"]
          enable_sso: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["enable_sso"]
          size: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["size"]
          type: >-
            local.elements_landing_zone_directory_service_map["config_${count.index}"]["type"]
          vpc_settings:
            vpc_id: data.aws_vpc.default_vpc.id
            subnet_ids:
              - data.aws_subnet.default_subnet.*.id
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.id)
      access_urls:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.access_url)
      aliases:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.alias)
      landing_zone_directory_service_directory_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.id)
      landing_zone_directory_service_directory_access_urls:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.access_url)
      landing_zone_directory_service_directory_aliases:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_directory_service_directory.landing_zone_directory_service_directory.*.alias)
