component:
  name: landing_zone_directory_service_directory
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_directory_service_directory/terraform.tfstate
    data:
      aws_vpc:
        default_vpc:
          provider: '${tfvar.terrahub["provider_alias"]}'
          default: true
      aws_subnet:
        default_subnet:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: >-
            ${length(var.landing_zone_directory_service_directory_availability_zones)}
          vpc_id: '${data.aws_vpc.default_vpc.id}'
          availability_zone: >-
            ${element(var.landing_zone_directory_service_directory_availability_zones,
            count.index)}
    resource:
      aws_directory_service_directory:
        landing_zone_directory_service_directory:
          provider: '${tfvar.terrahub["provider_alias"]}'
          name: '${var.landing_zone_directory_service_directory_name}'
          short_name: '${var.landing_zone_directory_service_directory_short_name}'
          password: '${var.landing_zone_directory_service_directory_password}'
          alias: '${var.landing_zone_directory_service_directory_alias}'
          description: '${var.landing_zone_directory_service_directory_description}'
          edition: '${var.landing_zone_directory_service_directory_edition}'
          enable_sso: '${var.landing_zone_directory_service_directory_enable_sso}'
          size: '${var.landing_zone_directory_service_directory_size}'
          type: '${var.landing_zone_directory_service_directory_type}'
          vpc_settings:
            vpc_id: '${data.aws_vpc.default_vpc.id}'
            subnet_ids:
              - '${data.aws_subnet.default_subnet.*.id}'
    output:
      id:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.id}
      thub_id:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.id}
      access_url:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.access_url}
      alias:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.alias}
      landing_zone_directory_service_directory_id:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.id}
      landing_zone_directory_service_directory_access_url:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.access_url}
      landing_zone_directory_service_directory_alias:
        value: >-
          ${aws_directory_service_directory.landing_zone_directory_service_directory.alias}
