## local config
component:
  name: landing_zone_subnet_public
  dependsOn:
    - ../landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: ${local.component["local"]}/landing_zone_subnet_public/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_vpc:
          backend: local
          config:
            path: '${local.component["local"]}/landing_zone_vpc/terraform.tfstate'
    resource:
      aws_subnet:
        landing_zone_subnet_public:
          count: '${length(var.landing_zone_subnet_public_cidr_block)}'
          vpc_id: '${data.terraform_remote_state.landing_zone_vpc.thub_id}'
          cidr_block: '${element(var.landing_zone_subnet_public_cidr_block, count.index)}'
          availability_zone: '${element(var.availability_zones, count.index)}'
          tags: '${merge(var.landing_zone_subnet_public_tags, map("Name", "Landing Zone Subnet Public ${element(var.availability_zones,count.index)}"))}'
          assign_ipv6_address_on_creation: '${var.landing_zone_subnet_public_assign_ipv6_address_on_creation}'
    output:
      ids:
        value: '${aws_subnet.landing_zone_subnet_public.*.id}'
      thub_ids:
        value: '${aws_subnet.landing_zone_subnet_public.*.id}'
      availability_zone_ids:
        value: '${aws_subnet.landing_zone_subnet_public.*.availability_zone_id}'
      arns:
        value: '${aws_subnet.landing_zone_subnet_public.*.arn}'
      landing_zone_subnet_public_ids:
        value: '${aws_subnet.landing_zone_subnet_public.*.id}'
      landing_zone_subnet_public_availability_zone_ids:
        value: '${aws_subnet.landing_zone_subnet_public.*.availability_zone_id}'
      landing_zone_subnet_public_arns:
        value: '${aws_subnet.landing_zone_subnet_public.*.arn}'
