component:
  name: landing_zone_organization_accounts
  dependsOn:
    - landing_zone_organization
  template:
    data:
      aws_organizations_organization:
        landing_zone_organization: {}
    resource:
      aws_organizations_account:
        landing_zone_organization_accounts:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(var.landing_zone_organization_accounts_emails)
          name: 'element(var.landing_zone_organization_accounts_names, count.index)'
          email: 'element(var.landing_zone_organization_accounts_emails, count.index)'
          parent_id: data.aws_organizations_organization.landing_zone_organization.roots.0.id
    output:
      ids:
        value: aws_organizations_account.landing_zone_organization_accounts.*.id
      thub_ids:
        value: aws_organizations_account.landing_zone_organization_accounts.*.id
      arns:
        value: aws_organizations_account.landing_zone_organization_accounts.*.arn
      landing_zone_organization_accounts_ids:
        value: aws_organizations_account.landing_zone_organization_accounts.*.id
      landing_zone_organization_accounts_arns:
        value: aws_organizations_account.landing_zone_organization_accounts.*.arn
