component:
  name: landing_zone_cloudtrail_s3_bucket_policy
  dependsOn:
    - ../landing_zone_cloudtrail_s3_bucket
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_cloudtrail_s3_bucket_policy/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_cloudtrail_s3_bucket:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_cloudtrail_s3_bucket/terraform.tfstate
      template_file:
        landing_zone_cloudtrail_s3_bucket_policy:
          template: 'file("${local.component["path"]}/policy.json.tpl")'
          vars:
            s3_bucket_name: >-
              data.terraform_remote_state.landing_zone_cloudtrail_s3_bucket.bucket
            account_id: var.account_id
    resource:
      aws_s3_bucket_policy:
        landing_zone_cloudtrail_s3_bucket_policy:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          bucket: data.terraform_remote_state.landing_zone_cloudtrail_s3_bucket.bucket
          policy: data.template_file.landing_zone_cloudtrail_s3_bucket_policy.rendered
