component:
  name: landing_zone_route_table
  dependsOn:
    - ../landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_route_table/terraform.tfstate
    data:
      aws_vpc:
        selected:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_vpc_cidr_blocks)}'
          cidr_block: '${element(var.landing_zone_vpc_cidr_blocks, count.index)}'
    resource:
      aws_route_table:
        landing_zone_route_table:
          provider: '${tfvar.terrahub["provider_alias"]}'
          count: '${length(var.landing_zone_route_table_names)}'
          vpc_id: '${element(data.aws_vpc.selected.*.id, count.index)}'
          tags: >-
            ${merge(var.landing_zone_route_table_tags, map("Name",
            "${element(var.landing_zone_route_table_names, count.index)}"))}
          propagating_vgws: '${var.landing_zone_route_table_propagating_vgws}'
    output:
      ids:
        value: '${aws_route_table.landing_zone_route_table.*.id}'
      thub_ids:
        value: '${aws_route_table.landing_zone_route_table.*.id}'
      landing_zone_route_table_ids:
        value: '${aws_route_table.landing_zone_route_table.*.id}'
terraform:
  varFile:
    - ../mitocgroup_tfvars/landing_zone_route_table/default.tfvars
