component:
  name: landing_zone_route_table
  dependsOn:
    - ../landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_route_table/terraform.tfstate
    locals:
      elements_landing_zone_vpc_data_map: >-
        ${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]}
      elements_landing_zone_vpc_data_count: >-
        ${length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])}
      elements_landing_zone_route_table_map: >-
        ${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_resource"]}
      elements_landing_zone_route_table_tags_map: >-
        ${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_tags_element"]}
      elements_landing_zone_route_table_count: >-
        ${length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_resource"])}
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: '${local.elements_landing_zone_vpc_data_count}'
          cidr_block: >-
            ${lookup(local.elements_landing_zone_vpc_data_map["config_${count.index}"],
            "cidr_block")}
    resource:
      aws_route_table:
        landing_zone_route_table:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: '${local.elements_landing_zone_route_table_count}'
          vpc_id: '${element(data.aws_vpc.vpc_selected.*.id, count.index)}'
          tags: >-
            ${local.elements_landing_zone_route_table_tags_map["config_${count.index}"]}
          propagating_vgws: >-
            ${split("|",
            lookup(local.elements_landing_zone_route_table_map["config_${count.index}"],
            "propagating_vgws"))}
    output:
      ids:
        value: >-
          ${map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route_table.landing_zone_route_table.*.id)}
      thub_ids:
        value: >-
          ${map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route_table.landing_zone_route_table.*.id)}
      landing_zone_route_table_ids:
        value: >-
          ${map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route_table.landing_zone_route_table.*.id)}
