## local config
component:
  name: landing_zone_pipeline_s3_bucket
  template:
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-aws-landing-zone/landing_zone_pipeline_s3_bucket/terraform.tfstate
    resource:
      aws_s3_bucket:
        landing_zone_pipeline_s3_bucket:
          bucket: '${var.landing_zone_pipeline_s3_bucket_name}-${var.account_id}-${var.region}'
        versioning:
          enabled: '${var.landing_zone_pipeline_s3_bucket_versioning}'
    tfvars:
      landing_zone_pipeline_s3_bucket_name: 'aws-landing-zone-configuration'
      landing_zone_pipeline_s3_bucket_versioning: true
    output:
      id:
        value: '${aws_s3_bucket.landing_zone_pipeline_s3_bucket.id}'
      thub_id:
        value: '${aws_s3_bucket.landing_zone_pipeline_s3_bucket.id}'
      arn:
        value: '${aws_s3_bucket.landing_zone_pipeline_s3_bucket.arn}'
