component:
  name: landing_zone_route_tgw
  dependsOn:
    - ../landing_zone_route_table_tgw
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_route_tgw/terraform.tfstate
    locals:
      elements_landing_zone_route_tgw_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_tgw_resource"]
      elements_landing_zone_route_tgw_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_tgw_resource"])
    data:
      terraform_remote_state:
        landing_zone_route_table_tgw:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_route_table_tgw/terraform.tfstate
    resource:
      aws_route:
        landing_zone_route_tgw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_route_tgw_count
          transit_gateway_route_table_id: >-
            element(data.terraform_remote_state.landing_zone_route_table_tgw.thub_ids,
            count.index)
          destination_cidr_block: >-
            local.elements_landing_zone_route_tgw_map["config_${count.index}"]["destination_cidr_block"]
          blackhole: >-
            local.elements_landing_zone_route_tgw_map["config_${count.index}"]["blackhole"]
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route.landing_zone_route_tgw.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route.landing_zone_route_tgw.*.id)
      landing_zone_route_tgw_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route.landing_zone_route_tgw.*.id)
