component:
  name: landing_zone_network_acl_rules
  dependsOn:
    - ../landing_zone_network_acl
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_network_acl_rules/terraform.tfstate
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_vpc_data_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
      elements_landing_zone_landing_zone_network_acl_rules_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_network_acl_rule_resource"]
      elements_landing_zone_landing_zone_network_acl_rules_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_network_acl_rule_resource"])
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_vpc_data_count
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_network_acls:
        network_acls_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(data.aws_vpc.vpc_selected.*.id)
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
    resource:
      aws_network_acl_rule:
        landing_zone_network_acl_rules:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_landing_zone_network_acl_rules_count
          network_acl_id: >-
            element(data.aws_network_acls.network_acls_selected.ids,
            count.index)
          rule_number: >-
            local.elements_landing_zone_landing_zone_network_acl_rules_map["config_${count.index}"]["rule_number"]
          protocol: >-
            local.elements_landing_zone_landing_zone_network_acl_rules_map["config_${count.index}"]["protocol"]
          rule_action: >-
            local.elements_landing_zone_landing_zone_network_acl_rules_map["config_${count.index}"]["rule_action"]
          egress: >-
            local.elements_landing_zone_landing_zone_network_acl_rules_map["config_${count.index}"]["egress"]
          cidr_block: >-
            local.elements_landing_zone_landing_zone_network_acl_rules_map["config_${count.index}"]["cidr_block"]
