component:
  name: terrahub_load_outputs
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/terrahub_load_outputs/terraform.tfstate
    output:
      terrahub_reader:
        value: >-
          '${map("arns",data.terraform_remote_state.landing_zone_vpc.arns,"landing_zone_vpc_arns",data.terraform_remote_state.landing_zone_vpc.landing_zone_vpc_arns,"thub_ids",data.terraform_remote_state.landing_zone_vpc.thub_ids,"ids",data.terraform_remote_state.landing_zone_vpc.ids,"landing_zone_vpc_ids",data.terraform_remote_state.landing_zone_vpc.landing_zone_vpc_ids)}'
    data:
      terraform_remote_state:
        landing_zone_subnet:
          backend: local
          config:
            path: >-
              '${tfvar.terrahub["tfstate_path"]}/landing_zone_subnet/terraform.tfstate'
        landing_zone_vpc:
          backend: local
          config:
            path: >-
              '${tfvar.terrahub["tfstate_path"]}/landing_zone_vpc/terraform.tfstate'
template:
  output:
    terrahub_reader:
      value: >-
        '${map("arns",data.terraform_remote_state.landing_zone_vpc.arns,"landing_zone_vpc_arns",data.terraform_remote_state.landing_zone_vpc.landing_zone_vpc_arns,"thub_ids",data.terraform_remote_state.landing_zone_vpc.thub_ids,"ids",data.terraform_remote_state.landing_zone_vpc.ids,"landing_zone_vpc_ids",data.terraform_remote_state.landing_zone_vpc.landing_zone_vpc_ids)}'
  data:
    terraform_remote_state:
      landing_zone_subnet:
        backend: local
        config:
          path: >-
            '${tfvar.terrahub["tfstate_path"]}/landing_zone_subnet/terraform.tfstate'
      landing_zone_vpc:
        backend: local
        config:
          path: >-
            '${tfvar.terrahub["tfstate_path"]}/landing_zone_vpc/terraform.tfstate'
