component:
  name: terrahub_load_outputs
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/terrahub_load_outputs/terraform.tfstate
    output:
      terrahub_reader:
        value: >-
          ${map("OUTPUT_KEY", "OUTPUT_VALUE")}
