component:
  name: terrahub_load_outputs
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/terrahub_load_outputs/terraform.tfstate
    resource:
      null_resource:
        everytime:
          triggers:
            timestamp: timestamp()
    output:
      terrahub_reader:
        value: >-
          merge(map("ids",data.terraform_remote_state.landing_zone_security_group.outputs.ids,"landing_zone_security_group_ids",data.terraform_remote_state.landing_zone_security_group.outputs.landing_zone_security_group_ids,"thub_ids",data.terraform_remote_state.landing_zone_security_group.outputs.thub_ids),map("arns",data.terraform_remote_state.landing_zone_subnet.outputs.arns,"availability_zone_ids",data.terraform_remote_state.landing_zone_subnet.outputs.availability_zone_ids,"ids",data.terraform_remote_state.landing_zone_subnet.outputs.ids,"landing_zone_subnet_arns",data.terraform_remote_state.landing_zone_subnet.outputs.landing_zone_subnet_arns,"landing_zone_subnet_availability_zone_ids",data.terraform_remote_state.landing_zone_subnet.outputs.landing_zone_subnet_availability_zone_ids,"landing_zone_subnet_ids",data.terraform_remote_state.landing_zone_subnet.outputs.landing_zone_subnet_ids,"thub_ids",data.terraform_remote_state.landing_zone_subnet.outputs.thub_ids),map("arns",data.terraform_remote_state.landing_zone_vpc.outputs.arns,"ids",data.terraform_remote_state.landing_zone_vpc.outputs.ids,"landing_zone_vpc_arns",data.terraform_remote_state.landing_zone_vpc.outputs.landing_zone_vpc_arns,"landing_zone_vpc_ids",data.terraform_remote_state.landing_zone_vpc.outputs.landing_zone_vpc_ids,"thub_ids",data.terraform_remote_state.landing_zone_vpc.outputs.thub_ids))
