## local config
component:
  name: landing_zone_code_build_role
  template:
    terraform:
      backend:
        local:
          path: >-
            /tmp/.terrahub/local_backend/terraform-aws-landing-zone/landing_zone_code_build_role/terraform.tfstate
    resource:
      aws_iam_role:
        landing_zone_code_build_role:
          assume_role_policy: '${file("${local.component["path"]}/iam_trust_policy.json.tpl")}'
          description: '${var.landing_zone_code_build_role_description}'
          force_detach_policies: '${var.landing_zone_code_build_role_force_detach_policies}'
          name: '${var.landing_zone_code_build_role_name}'
          path: '${var.landing_zone_code_build_role_path}'
    output:
      id:
        value: '${aws_iam_role.landing_zone_code_build_role.id}'
      thub_id:
        value: '${aws_iam_role.landing_zone_code_build_role.id}'
      name:
        value: '${aws_iam_role.landing_zone_code_build_role.name}'
      arn:
        value: '${aws_iam_role.landing_zone_code_build_role.arn}'
      landing_zone_code_build_role_id:
        value: '${aws_iam_role.landing_zone_code_build_role.id}'
      landing_zone_code_build_role_name:
        value: '${aws_iam_role.landing_zone_code_build_role.name}'
      landing_zone_code_build_role_arn:
        value: '${aws_iam_role.landing_zone_code_build_role.arn}'

