component:
  name: landing_zone_ssm_association_version_2
  template:
    locals:
      elements_landing_zone_ssm_association_version_2_arg_parameters_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_association_version_2_resource_arg_parameters"]
      elements_landing_zone_ssm_association_version_2_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_association_version_2_resource"]
    resource:
      aws_ssm_association:
        landing_zone_ssm_association_version_2:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_association_version_2_resource"])
          name: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["name"]
          association_name: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["association_name"]
          document_version: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["document_version"]
          output_location:
            s3_bucket_name: >-
              local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["ol_s3_bucket_name"]
            s3_key_prefix: >-
              local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["ol_s3_key_prefix"]
          parameters: >-
            local.elements_landing_zone_ssm_association_version_2_arg_parameters_map["config_${count.index}"]
          schedule_expression: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["schedule_expression"]
          compliance_severity: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["compliance_severity"]
          max_concurrency: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["max_concurrency"]
          max_errors: >-
            local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["max_errors"]
          targets:
            - key: >-
                local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["targets_key_1"]
              values:
                - >-
                  local.elements_landing_zone_ssm_association_version_2_map["config_${count.index}"]["targets_value_1"]
    output:
      association_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_association.landing_zone_ssm_association_version_2.*.association_id)
      instance_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_association.landing_zone_ssm_association_version_2.*.instance_id)
      names:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_association.landing_zone_ssm_association_version_2.*.name)
      parameters:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_association.landing_zone_ssm_association_version_2.*.parameters)
      landing_zone_ssm_association_version_2_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_association.landing_zone_ssm_association_version_2.*.association_id)
      landing_zone_ssm_association_version_2_names:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_association.landing_zone_ssm_association_version_2.*.name)
