component:
  name: landing_zone_gateway_attachment_tgw
  dependsOn:
    - ../landing_zone_vpc
    - ../landing_zone_subnet
    - ../landing_zone_gateway_tgw
  template:
    locals:
      elements_landing_zone_gateway_tgw_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_tgw_data"]
      elements_vpc_selected_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_selected_data"]
      elements_subnet_selected_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_selected_data"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_selected_data"])
          cidr_block: >-
            local.elements_vpc_selected_data_map["config_${count.index}"]["cidr_block"]
      aws_subnet:
        subnet_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_selected_data"])
          cidr_block: >-
            local.elements_subnet_selected_data_map["config_${count.index}"]["cidr_block"]
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
      aws_ec2_transit_gateway:
        gateway_tgw_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_tgw_data"])
          filter:
            - name: options.amazon-side-asn
              values:
                - >-
                  local.elements_landing_zone_gateway_tgw_data_map["config_${count.index}"]["amazon_side_asn"]
    resource:
      aws_ec2_transit_gateway:
        landing_zone_gateway_attachment_tgw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_selected_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          subnet_ids: >-
            slice(tolist(data.aws_subnet_ids.subnet_selected[count.index].ids),
            local.elements_landing_zone_subnet_data_map["config_${count.index}"]["subnets_from_index"],
            local.elements_landing_zone_subnet_data_map["config_${count.index}"]["subnets_to_index"]) 
          transit_gateway_id: >-
            element(data.aws_ec2_transit_gateway.gateway_tgw_selected.*.id,
            count.index)
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ec2_transit_gateway.landing_zone_gateway_attachment_tgw.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ec2_transit_gateway.landing_zone_gateway_attachment_tgw.*.id)
      landing_zone_gateway_attachment_tgw_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ec2_transit_gateway.landing_zone_gateway_attachment_tgw.*.id)
