component:
  name: landing_zone_route
  dependsOn:
    - ../landing_zone_route_table
  template:
    terraform:
      backend:
        local:
          path: '${local.component["local"]}/landing_zone_route/terraform.tfstate'
    data:
      aws_subnet:
        selected:
          count: '${length(var.landing_zone_subnet_cidr_block)}'
          cidr_block: '${element(var.landing_zone_subnet_cidr_block, count.index)}'
      aws_route_table:
        selected:
          count: '${length(data.aws_subnet.selected.*.id)}'
          subnet_id: '${element(data.aws_subnet.selected.*.id, count.index)}'
    resource:
      aws_route:
        landing_zone_route:
          count: >-
            ${length(distinct(data.aws_route_table.selected.*.id)) *
            length(var.landing_zone_route_destination_cidr_block)}
          route_table_id: >-
            ${element(distinct(data.aws_route_table.selected.*.id),
            count.index)}
          destination_cidr_block: >-
            ${element(var.landing_zone_route_destination_cidr_block,
            count.index)}
    output:
      ids:
        value: '${aws_route.landing_zone_route.*.id}'
      thub_ids:
        value: '${aws_route.landing_zone_route.*.id}'
      landing_zone_route_ids:
        value: '${aws_route.landing_zone_route.*.id}'
