component:
  name: landing_zone_route
  dependsOn:
    - ../landing_zone_route_table
    - ../landing_zone_route_table_association
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_route/terraform.tfstate
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_vpc_data_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
      elements_landing_zone_subnet_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_data"]
      elements_landing_zone_subnet_data_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_data"])
      elements_landing_zone_route_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_resource"]
      elements_landing_zone_route_count: >-
        length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_resource"])
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_vpc_data_count
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_subnet:
        subnet_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_subnet_data_count
          cidr_block: >-
            local.elements_landing_zone_subnet_data_map["config_${count.index}"]["cidr_block"]
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
      aws_route_table:
        route_table_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(data.aws_subnet.subnet_selected.*.id)
          subnet_id: 'element(data.aws_subnet.subnet_selected.*.id, count.index)'
    resource:
      aws_route:
        landing_zone_route:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: local.elements_landing_zone_route_count
          route_table_id: >-
            element(distinct(data.aws_route_table.route_table_selected.*.id),
            count.index)
          destination_cidr_block: >-
            local.elements_landing_zone_route_map["config_${count.index}"]["destination_cidr_block"]
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route.landing_zone_route.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route.landing_zone_route.*.id)
      landing_zone_route_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_route.landing_zone_route.*.id)
