component:
  name: landing_zone_ssm_patch_group
  template:
    locals:
      elements_landing_zone_ssm_patch_group_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_patch_group_resource"]
    data:
      terraform_remote_state:
        landing_zone_ssm_patch_baseline:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_ssm_patch_group/terraform.tfstate
    resource:
      aws_ssm_patch_group:
        landing_zone_ssm_patch_group:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_patch_group_resource"])
          patch_group: >-
            local.elements_landing_zone_ssm_patch_group_map["config_${count.index}"]["patch_group"]
          baseline_id: >-
            element(data.terraform_remote_state.landing_zone_ssm_patch_baseline.outputs.ids["${tfvar.terrahub["landing_zone_providers"]["0"]}"],
            count.index)
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_patch_baseline.landing_zone_ssm_patch_group.*.id)
      landing_zone_ssm_patch_group_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_ssm_patch_baseline.landing_zone_ssm_patch_group.*.id)
