component:
  name: landing_zone_security_group_rule_ingress
  dependsOn:
    - ../landing_zone_security_group
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/landing_zone_security_group_rule_ingress/terraform.tfstate
    locals:
      elements_landing_zone_vpc_data_map: >-
        ${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]}
      elements_landing_zone_vpc_data_count: >-
        ${length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])}
      elements_landing_zone_security_group_data_map: >-
        ${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_data"]}
      elements_landing_zone_security_group_data_count: >-
        ${length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_data"])}
      elements_landing_zone_security_group_rule_map: >-
        ${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_rule_resource"]}
      elements_landing_zone_security_group_rule_count: >-
        ${length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_rule_resource"])}
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: '${local.elements_landing_zone_vpc_data_count}'
          cidr_block: >-
            ${lookup(local.elements_landing_zone_vpc_data_map["config_${count.index}"],
            "cidr_block")}
      aws_security_group:
        security_group_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: '${local.elements_landing_zone_security_group_data_count}'
          vpc_id: '${element(data.aws_vpc.vpc_selected.*.id, count.index)}'
          name: >-
            ${lookup(local.elements_landing_zone_security_group_data_map["config_${count.index}"],
            "name")}
    resource:
      aws_security_group_rule:
        landing_zone_security_group_rule_ingress:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: '${local.elements_landing_zone_security_group_rule_count}'
          type: ingress
          protocol: >-
            ${lookup(local.elements_landing_zone_security_group_rule_map["config_${count.index}"],
            "protocol")}
          from_port: >-
            ${lookup(local.elements_landing_zone_security_group_rule_map["config_${count.index}"],
            "from_port")}
          to_port: >-
            ${lookup(local.elements_landing_zone_security_group_rule_map["config_${count.index}"],
            "to_port")}
          security_group_id: >-
            ${element(data.aws_security_group.security_group_selected.*.id,
            count.index)}
          self: >-
            ${lookup(local.elements_landing_zone_security_group_rule_map["config_${count.index}"],
            "self")}
    output:
      ids:
        value: >-
          ${map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group_rule.landing_zone_security_group_rule_ingress.*.id)}
      thub_ids:
        value: >-
          ${map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group_rule.landing_zone_security_group_rule_ingress.*.id)}
