component:
  name: landing_zone_internet_gateway
  dependsOn:
    - ../landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: >-
            ${local.component["local"]}/landing_zone_internet_gateway/terraform.tfstate
    data:
      aws_vpc:
        selected:
          count: '${length(var.landing_zone_vpc_cidr_blocks)}'
          cidr_block: '${element(var.landing_zone_vpc_cidr_blocks, count.index)}'
    resource:
      aws_internet_gateway:
        landing_zone_internet_gateway:
          count: '${length(var.landing_zone_internet_gateway_names)}'
          vpc_id: '${element(data.aws_vpc.selected.*.id, count.index)}'
          tags: >-
            ${merge(var.landing_zone_internet_gateway_tags, map("Name",
            "${element(var.landing_zone_internet_gateway_names,
            count.index)}"))}
    output:
      ids:
        value: '${aws_internet_gateway.landing_zone_internet_gateway.*.id}'
      thub_ids:
        value: '${aws_internet_gateway.landing_zone_internet_gateway.*.id}'
      landing_zone_internet_gateway_ids:
        value: '${aws_internet_gateway.landing_zone_internet_gateway.*.id}'
