component:
  name: landing_zone_security_group_private
  dependsOn:
    - ../landing_zone_vpc
  template:
    terraform:
      backend:
        local:
          path: >-
            ${local.component["local"]}/landing_zone_security_group_private/terraform.tfstate
    data:
      terraform_remote_state:
        landing_zone_vpc:
          backend: local
          config:
            path: '${local.component["local"]}/landing_zone_vpc/terraform.tfstate'
    resource:
      aws_security_group:
        landing_zone_security_group_private:
          name: '${var.landing_zone_security_group_private_name}'
          description: '${var.landing_zone_security_group_private_description}'
          vpc_id: '${data.terraform_remote_state.landing_zone_vpc.thub_id}'
          tags: '${var.landing_zone_security_group_private_tags}'
    output:
      id:
        value: '${aws_security_group.landing_zone_security_group_private.id}'
      thub_id:
        value: '${aws_security_group.landing_zone_security_group_private.id}'
      landing_zone_security_group_private_id:
        value: '${aws_security_group.landing_zone_security_group_private.id}'
